model:
  name: "fpn_efficientnet"
  backbone: "efficientnet_b3"
  pretrained: true
  num_classes: 21
  fpn_channels: 96
  dropout: 0.1

data:
  root: "/content/datasets"
  input_size: 512
  num_workers: 2
  pin_memory: true
  ignore_index: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

  train_datasets:
    - name: "voc"
      year: "2007"
      split: "train"
    - name: "voc"
      year: "2012"
      split: "train"
    - name: "coco_voc"
      split: "train"

  val_dataset:
    name: "voc"
    year: "2012"
    split: "val"

  coco:
    image_dir: "/content/datasets/coco/train2017"
    ann_file: "/content/datasets/coco/annotations/instances_train2017.json"
    use_mask_cache: true
    mask_cache_dir: "/content/datasets/coco/coco_voc_mask_cache"

transforms:
  hflip_prob: 0.5

  random_scale_prob: 1.0
  scale_range: [0.5, 2.0]

  random_crop_prob: 1.0

  copy_paste_prob: 0.2
  paste_scale_range: [0.5, 1.5]

  stitching_prob: 0.0

  color_jitter_prob: 0.4

training:
  batch_size: 16
  epochs: 60
  backbone_lr: 1.0e-4
  head_lr: 1.0e-3
  weight_decay: 1.0e-4
  scheduler: "exponential"
  lr_decay: 0.9995
  eval_interval: 2
  amp: true

checkpoint:
  save_dir: "/content/drive/MyDrive/project1_checkpoints"
  resume_path: "/content/drive/MyDrive/project1_checkpoints/best2.pth"

wandb:
  entity: "jyun_chae-sungkyunkwan-university"
  project: "open_ai_proj1"
  run_name: "efficientnet_b3_fpn96"

runtime:
  device: "cuda"
  seed: 42

submit:
  img_dir: "/content/project01/submit/img"
  pred_dir: "/content/project01/submit/pred"