model:
  name: "fpn_efficientnet"
  backbone: "efficientnet_b3"
  dropout: 0.1
  num_classes: 21
  pretrained: true
  fpn_channels: 96

data:
  dataset_name: "VOC"
  num_workers: 2
  pin_memory: true
  input_size: 512
  num_classes: 21

  use_coco_mask_cache: true
  coco_mask_cache_dir: "/content/datasets/coco/coco_voc_mask_cache"

  root: "/content/datasets"
  coco_root: "/content/datasets/coco/train2017"
  coco_ann_file: "/content/datasets/coco/annotations/instances_train2017.json"

  train_datasets:
    - name: VOC
      year: "2007"
      split: train
    - name: VOC
      year: "2012"
      split: train
    - name: coco_voc
      split: train
  
  val_dataset:
    name: VOC
    year: "2012"
    split: val

training:
  batch_size: 16
  epochs: 60
  backbone_lr: 1.0e-4
  head_lr: 1.0e-3
  weight_decay: 1.0e-4
  lr_decay: 0.9995
  ignore_index: 255
  eval_interval: 2

checkpoint:
  save_dir: "/content/drive/MyDrive/project1_checkpoints"
  save_every: 5
  resume_path: ""

wandb:
  team: "jyun_chae-sungkyunkwan-university"
  project: "open_ai_proj1"
  run_name: "efficientnet_b0_1"

device: "cuda"
seed: 42

flops:
  height: 480
  width: 640

paths:
  submit_img_dir: "/content/project01/submit/img"
  pred_dir: "/content/project01/submit/pred"